baseURL = ''
languageCode = 'en-us'
title = 'raw input'

theme = "hugo-theme-m10c"

[pagination]
  pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "input"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "sobre"
    url = "/about/"
    weight = 2

[params]
  author = "gabriel"
  description = "homem cis hétero, 23 anos, 183cm, nerd"
  menu_item_separator = "|"
  avatar = "avatar.jpg"
  [[params.social]]
    icon = "brand-myanimelist"
    name = "MyAnimeList"
    url = "https://myanimelist.net/profile/_Arch___"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/cauzinnn"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/_nobre___"
  [[params.social]]
    icon = "brand-whatsapp"
    name = "Whatsapp"
    url = "https://wa.me/+5521975432887"
  [[params.social]]
    icon = "brand-letterboxd"
    name = "Letterboxd"
    url = "https://letterboxd.com/cauzinn/"

  # Default theme
  [params.style]
    darkestColor = "#25282e"
    darkColor = "#2e3440"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#81a1c1"

  # Green theme
  # [params.style]
  #   darkestColor = "#315659"
  #   darkColor = "#253031"
  #   lightColor = "#96a879"
  #   lightestColor = "#fff"
  #   primaryColor = "#dad865"

  # Red theme
  # [params.style]
  #   darkestColor = "#d35050"
  #   darkColor = "#212121"
  #   lightColor = "#d6d6d6"
  #   lightestColor = "#d3d3d3"
  #   primaryColor = "#ffffff"
